spring:
    datasource:
        url: jdbc:mysql://localhost:3306/order-food
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

mybatis:
    mapper-locations: classpath*:mybatis/**/*.xml
    type-aliases-package: order.food.**.response
